version: '3.8'

services:
  # PostgreSQL para Auth Service
  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - microservices-net
    restart: unless-stopped

  # PostgreSQL para Stock Service
  postgres-stock:
    image: postgres:15
    container_name: postgres-stock
    environment:
      POSTGRES_DB: stockdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - postgres_stock_data:/var/lib/postgresql/data
    networks:
      - microservices-net
    restart: unless-stopped

  # PostgreSQL para Sales Service
  postgres-sales:
    image: postgres:15
    container_name: postgres-sales
    environment:
      POSTGRES_DB: salesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5434:5432"
    volumes:
      - postgres_sales_data:/var/lib/postgresql/data
    networks:
      - microservices-net
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # Porta AMQP
      - "15672:15672" # Porta Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - microservices-net
    restart: unless-stopped

volumes:
  postgres_auth_data:
  postgres_stock_data:
  postgres_sales_data:
  rabbitmq_data:

networks:
  microservices-net:
    driver: bridge
